name: Register flows (staging)

on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/cd_staging.yaml"
      - "pipelines/**/*"
      - "pyproject.toml"
      - "Dockerfile"

# Improvement #2: Cancel existing executions when new commits are pushed onto the branch
# [Ref] https://ashishb.net/programming/common-pitfalls-of-github-actions/
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PREFECT__BACKEND: cloud
  PREFECT__CLOUD__API: ${{ secrets.PREFECT__CLOUD__API }}
  PREFECT__CLOUD__PORT: ${{ secrets.PREFECT__CLOUD__PORT }}
  PREFECT__SERVER__PROJECT: ${{ secrets.PREFECT__SERVER__PROJECT__STAGING }}
  PREFECT_AUTH_TOML: ${{ secrets.PREFECT_AUTH_TOML }}

jobs:
  build-container:
    if: startsWith(github.head_ref, 'staging/') || contains( github.event.pull_request.labels.*.name, 'staging')
    name: Register flows (staging)
    runs-on: ubuntu-latest
    # Improvement #4: Add a timeout of 30 mins
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v6

      - name: Setup Python version
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Setup Google Cloud credentials
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      # Improvement #5: Cache Python dependencies using the hash of "requirements.txt" as the key
      # This step must be executed before "pip install"
      - uses: actions/cache@v5
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pypoetry
          key: ${{ runner.os }}-pip-poetry-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-poetry-

      - name: Install Python dependencies for deploying
        run: |-
          pip install -U pip poetry==1.7.1
          poetry config virtualenvs.create false
          poetry install --with dev --with ci

      - name: Update image tag in constants
        run: |-
          python .github/workflows/scripts/replace_docker_tag.py ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }} ${{ github.sha }}

      - name: Set Infisical data in constants
        run: |-
          python .github/workflows/scripts/replace_infisical_data.py ${{ secrets.CONSTANTS_INFISICAL_ADDRESS }} ${{ secrets.CONSTANTS_INFISICAL_TOKEN }}

      - name: Get changed files for code tree analysis
        id: files
        uses: Ana06/get-changed-files@v2.3.0

      - name: Perform code tree analysis
        id: code-tree-analysis
        continue-on-error: true
        run: |
          python .github/workflows/scripts/code_tree_analysis.py "${{ steps.files.outputs.all }}" --write-to-file

      - name: Write auth.toml
        run: |-
          mkdir -p $HOME/.prefect
          echo $PREFECT_AUTH_TOML | base64 --decode > $HOME/.prefect/auth.toml

      - name: Wait for GHCR image to be available
        uses: lewagon/wait-on-check-action@v1.4.1
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          check-name: 'GitHub Container Registry'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          verbose: true

      - name: Wait for GAR image to be available
        uses: lewagon/wait-on-check-action@v1.4.1
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          check-name: 'Google Artifact Registry'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          verbose: true

      - name: Register Prefect flows
        run: |-
          python .github/workflows/scripts/register_flows.py --project $PREFECT__SERVER__PROJECT --path pipelines/ --no-schedule --filter-affected-flows

      - name: Delete Ghost Flows
        run: |-
          python .github/workflows/scripts/delete_ghost_flows.py --project $PREFECT__SERVER__PROJECT --environment prod
