name: CI

on:
  pull_request:

# Improvement #2: Cancel existing executions when new commits are pushed onto the branch
# [Ref] https://ashishb.net/programming/common-pitfalls-of-github-actions/
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-tree-analysis:
    name: Code tree analysis
    runs-on: ubuntu-latest
    # Improvement #4: Add a timeout of 30 mins
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v6

      - name: Setup Python version
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      # Improvement #5: Cache Python dependencies using the hash of "requirements.txt" as the key
      # This step must be executed before "pip install"
      - uses: actions/cache@v5
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pypoetry
          key: ${{ runner.os }}-pip-poetry-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-poetry-

      - name: Install Python dependencies for deploying
        run: |-
          pip install -U pip poetry==1.7.1
          poetry config virtualenvs.create false
          poetry install --with dev --with ci

      - name: Check if `prefect build` works
        run: |
          prefect build

      - name: Get changed files for code tree analysis
        id: files
        uses: Ana06/get-changed-files@v2.3.0

      - name: Perform code tree analysis
        id: code-tree-analysis
        continue-on-error: true
        run: |
          python .github/workflows/scripts/code_tree_analysis.py "${{ steps.files.outputs.all }}"

      - name: Delete previous comments
        uses: izhangzhihao/delete-comment@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_user_name: github-actions[bot]
          issue_number: ${{ github.event.number }}  #remove comments from the current PR

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3.0.1
        with:
          message: "${{ steps.code-tree-analysis.outputs.pr-message }}"
          github-token: ${{ secrets.GITHUB_TOKEN }}
